---
title: "Charts_for_2020_06_09"
output: html_document
---

```{r message=FALSE, echo=FALSE}
# Load the data
defaultW <- getOption("warn") #turn off the warnings
options(warn = -1) #turn off all warnings
library(readr)
library(tidyverse)
library(astsa)
library(scales)
library(ggplot2)
library(caret)
library(e1071)
ridership <- read_csv("trips_data_by_day.csv", 
                      col_names = c(
                        "trip_day",
                        "trip_count",
                        "mean_trip_length",
                        "trip_hours",
                        "city"
                      ),
                      col_types=cols(
                        trip_day = col_date(),
                        trip_count = col_integer(),
                        mean_trip_length = col_double(),
                        trip_hours = col_double(),
                        city = col_character()
                      ))

weather  <- read_csv("noaa_weather_central_park.csv")
```

```{r}
nyc_ridership <- ridership %>% 
  filter(city == "NYC")%>%
  left_join(weather, by = c("trip_day"="DATE")) %>%
  select(
    trip_day
    , trip_count
    , AWND
    , PRCP
    , SNOW
    , SNWD
    , TMAX
    , TMIN
    , WDF2
    , WDF5
    , WSF2
    , WSF5
  ) %>%
  mutate(
    ridership_average_7 = stats::filter(trip_count, sides=2, filter=rep(1/7,7))
    , ridership_average_31 = stats::filter(trip_count, sides=2, filter=rep(1/31,31))
    , day_of_week = weekdays(as.Date(trip_day))
    , weekend = if_else(day_of_week %in% c('Saturday','Sunday'),1,0)
    , days_line = trip_day - min(trip_day)
  )
```

```{r}
ggplot(data = nyc_ridership, mapping=aes(x=trip_day)) +
  geom_line(mapping = aes(y=trip_count), color = "orange") +
  geom_line(mapping =aes(y=ridership_average_31), color= "blue") +
  ggtitle("NYC Daily Citibike Trip Counts with 31 Day Moving Average") +
  scale_y_continuous(label=comma) +
  theme(plot.title = element_text(hjust=0.5, color = "white"),
        axis.title = element_blank()
  )
```
```{r}
ggplot(data = nyc_ridership, mapping=aes(x=trip_day)) +
  geom_line(mapping = aes(y=trip_count), color = "orange") +
  geom_line(mapping =aes(y=ridership_average_7), color= "blue") +
  ggtitle("NYC Daily Citibike Trip Counts with 7 Day Moving Average") +
  scale_y_continuous(label=comma) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title = element_blank()
  )
```


```{r}
nyc_ridership$log_trip_count <- log(nyc_ridership$trip_count)  #y = log transformation

ggplot(data = nyc_ridership, mapping=aes(x=trip_day)) +
  geom_line(mapping=aes(y=log_trip_count), color= "blue") +
  ggtitle("NYC Daily Citibike Total Trip Counts: Log Transformation") +
  # scale_y_continuous(label=percent) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title = element_blank())
```

```{r}
attach(nyc_ridership)
differenced_log_trip_count <- diff(log_trip_count)
row_count <- length(log_trip_count)


ggplot(mapping=aes(x=trip_day[2:row_count])) +
  geom_line(mapping=aes(y=diff(log_trip_count)), color= "orange") +
  geom_smooth(mapping=aes(y=diff(log_trip_count)), method="loess", color="blue") +
  ggtitle("NYC Daily Citibike Total Trip Counts: Differenced Log Transformation") +
  theme(plot.title = element_text(hjust=0.5),
        axis.title = element_blank())

detach()
```


```{r}
acf_differenced_log_trip_count = acf(differenced_log_trip_count, lag.max = 36, plot = FALSE)

plot(acf_differenced_log_trip_count, main = "TEST")

par(mfrow=c(1,1))
```
```{r}
attach(nyc_ridership)

tsplot(x=trip_day, y=trip_count/1000, main="NYC Total Daily Trips: KSmooth Transformation", col="orange", lwd=2, ylab = "Number of Trips/1000")
lines(ksmooth(x=trip_day, y=trip_count/1000, "normal", bandwidth = 12), col="blue", lwd=2)

detach()
```

```{r}
pacf_differenced_log_trip_count = pacf(differenced_log_trip_count, lag.max = 36)
```

```{r}
par(mfrow=c(3,1 ))
    
tsplot(x=nyc_ridership$trip_day, y=nyc_ridership$trip_count/1000, main = "NYC Daily Ridership", xlab="", ylab = "Daily Ridership (1000s)")

tsplot(x=nyc_ridership$trip_day, y=nyc_ridership$TMAX, col="red", xlab="", ylab = "Degrees F", main = "Maximum Central Park Daily Temperature")

tsplot(x=nyc_ridership$trip_day, y=nyc_ridership$TMIN, col="blue", xlab="", ylab = "Degrees F", main = "Minimum Central Park Daily Temperature")
```

```{r}
ggplot(data=nyc_ridership) +
  geom_density(mapping = aes(x=trip_count), color="orange") +
  geom_histogram(mapping = aes(x=trip_count, y = ..density..), alpha=0.25, color = "blue", fill = "blue") +
  geom_rug(aes(x = trip_count, y = 0), color = "blue") +
  ggtitle("Histogram of Untransformed Trip Counts") +
  xlab("Trip Count Bins") +
  theme(
    plot.title = element_text(hjust = 0.5)
    , axis.title.y = element_blank()
    , axis.text.y = element_blank()
  )
```

```{r}
ggplot() +
  geom_density(mapping = aes(x=differenced_log_trip_count), color="orange") +
  geom_histogram(mapping = aes(x=differenced_log_trip_count, y = ..density..), alpha=0.25, color = "blue", fill = "blue") +
  geom_rug(aes(x = differenced_log_trip_count, y = 0), color = "blue") +
  ggtitle("Histogram of Transformed Trip Counts") +
  xlab("Trip Count Bins") +
  theme(
    plot.title = element_text(hjust = 0.5)
    , axis.title.y = element_blank()
    , axis.text.y = element_blank()
  )
```

```{r}
check_day <- nyc_ridership %>%
  group_by(day_of_week) %>%
  summarise(mean_trips = mean(trip_count/1000))

ggplot(data=check_day) +
  geom_bar(mapping = aes(x=day_of_week, y=mean_trips), stat="identity", color = "blue", fill="blue", alpha=0.5) +
  ggtitle("Average Trips by Weekday") +
  ylab("Average Number of Trips (1000s)") +
  theme(plot.title = element_text(hjust=0.5)
        , axis.title.x = element_blank())
```



```{r}
model_data <- nyc_ridership %>% select(trip_count, AWND, PRCP, SNOW, SNWD, TMAX, TMIN, WDF2, WDF5, WSF2, WSF5, weekend, days_line)

model_data$AWND[is.na(model_data$AWND)] <- 0
model_data$PRCP[is.na(model_data$PRCP)] <- 0
model_data$SNOW[is.na(model_data$SNOW)] <- 0
model_data$SNWD[is.na(model_data$SNWD)] <- 0
model_data$TMAX[is.na(model_data$TMAX)] <- 0
model_data$TMIN[is.na(model_data$TMIN)] <- 0
model_data$WDF2[is.na(model_data$WDF2)] <- 0
model_data$WDF5[is.na(model_data$WDF5)] <- 0
model_data$WSF2[is.na(model_data$WSF2)] <- 0
model_data$WSF5[is.na(model_data$WSF5)] <- 0
model_data$weekend[is.na(model_data$weekend)] <- 0
model_data$days_line[is.na(model_data$days_line)] <- 0
```

```{r}
lmMod <- lm(trip_count ~ . , data = model_data)
selectedMod <- step(lmMod)
linear_models <- summary(selectedMod)
```

```{r}
ggplot(mapping = aes(y=linear_models$residuals, x=nyc_ridership$trip_day)) +
  geom_line(color = "red", alpha=0.25) +
  geom_smooth(method="loess", color="red", span = 0.1) +
  ggtitle("Linear Model Residual Plot") +
  scale_y_continuous(labels = scales::comma) +
  theme(plot.title = element_text(hjust=0.5)
        , axis.title.x = element_blank()
        , axis.title.y = element_blank())
```

```{r}
ggplot() +
  geom_density(mapping = aes(x=linear_models$residuals), color="black") +
  geom_histogram(mapping = aes(x=linear_models$residuals, y = ..density..), alpha=0.25, color = "red", fill = "red") +
  geom_rug(aes(x = linear_models$residuals, y = 0), color = "red", aes=0.1) +
  ggtitle("Histogram of Residuals") +
  scale_x_continuous(label=scales::comma) +
  theme(
    plot.title = element_text(hjust = 0.5)
    , axis.title.y = element_blank()
    , axis.text.y = element_blank()
    , axis.title.x = element_blank()
  )
```

```{r}
lmMod <- lm(trip_count ~ . , data = model_data)
selectedMod <- step(lmMod)
summary(selectedMod)
```

```{r}
fitted <- selectedMod$fitted.values
```

```{r}
ggplot(mapping = aes(x=nyc_ridership$trip_day)) +
  geom_line(mapping = aes(y=nyc_ridership$trip_count, alpha = 'Ride Counts', color = 'Ride Counts')) +
  geom_smooth(mapping = aes(y=nyc_ridership$trip_count, alpha = 'Smoothed Ride Counts', color = 'Smoothed Ride Counts'), method="loess", span = 0.1) +
  geom_line(mapping=aes(y=fitted, alpha = 'Predictions', color = 'Predictions')) +
  geom_smooth(mapping = aes(y=fitted, alpha = 'Smoothed Predictions', color = 'Smoothed Predictions'), method="loess", span = 0.1) +
  ggtitle("Predicted vs Actual Trips") +
  scale_y_continuous(labels = scales::comma) +
  ylab("Daily Trip Counts") +
  scale_colour_manual(name = "",values = c('Ride Counts'='blue', 'Smoothed Ride Counts'='blue', 'Predictions' = 'red', 'Smoothed Predictions' = 'red')) +
  scale_alpha_manual(name="",values = c('Ride Counts'=0.3, 'Smoothed Ride Counts' = 1, 'Predictions' = 0.3, 'Smoothed Predictions' = 1)) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.background = element_rect(fill='white'),
        legend.key = element_rect(fill="white"))
```


```{r}
attach(nyc_ridership)
nyc_ridership$square_trip_count <- nyc_ridership$trip_count^0.6
differenced_square_trip_count <- diff(nyc_ridership$square_trip_count)
row_count <- length(log_trip_count)

ggplot(mapping=aes(x=trip_day[2:row_count])) +
  geom_line(mapping=aes(y=differenced_square_trip_count), color= "blue") +
  ggtitle("NYC Daily Citibike Total Trip Counts: Box-Cox Transformation, ") +
  # scale_y_continuous(label=percent) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title = element_blank())

pacf(differenced_square_trip_count, lag.max = 24)
acf(differenced_square_trip_count, lag.max = 24)

detach(nyc_ridership)
```
```{r}
boxes <- caret::BoxCoxTrans(nyc_ridership$trip_count)
```


